### PR TITLE
Issue63 turbinelevel - Run DES at technology level instead of component level

### PR DESCRIPTION
**Pull request by rjhanes**
Merging this PR will address #63 

Question for @eberlea and @akey7 - When we run the simulation at the technology (turbine) level, our facility inventories no longer show the exact component (blade) count. The mass inventories by material are correct, and the count inventories for blades are simply off by a factor of 3. Is it worth adding a set of parameters to the config file that quantify the number of components in a technology, so we can scale the count inventories? I'm thinking something like:

```
components_per_technology
    - nacelle : 1
    - rotor : 1
    - foundation : 1
    - blade : 3
```

And then those values get passed into the diagnostic viz / results output code.

The only reason I can think of for not doing this is that I'm not sure this functionality is really needed for other renewable energy technologies.

### CODE REVIEW

**Review by akey7 — APPROVED** [review]
These changes look good to me! See my response to your comment in the other discussion.

**Comment by akey7** [comment]
Since error by a factor of 3 is isolated to the viz and output code, I think we can just fix those sections of code in a separate PR. Overall, I think it would be easier to make the assumption that all energy technologies would be in units of 1 (not 3) going forward, so we shouldn't need to lengthen the config file with more technology-specific parameters.

**Comment by eberlea** [comment]
@rjhanes I'm honestly torn about how to handle this issue. My instinct says that we should have a parameter set that indicates how many components there are per technology (I'm not thinking of a good example of where this might occur in other technologies at this moment but I suspect this isn't an isolated issue). However, I also don't want to bloat the config with unnecessary information. Would it make sense to have two configs (one that is primarily defaults that don't need to change) and the other that has parameters that vary more often? I don't think we need to incorporate this information into the main config file but we should keep track of it somewhere and we should report the correct counts for each component.

**Comment by rjhanes** [comment]
@eberlea Separating out the configs is sounding like a better idea the more I think about it, and maybe organizing the variables into different groups like file I/O, model run parameters, component- and material-specific parameters, and maybe a group that deals with uncertainty parameters. The default or static config file could consist of file I/O and maybe model run parameters. @akey7 , let's spend a bit of time at the next hackathon discussing before we create an issue.

I would like to avoid hard-coding anything to do with component counts, because I think we'd need to re-write the hard coded bits reasonably soon anyway. With that in mind, I propose adding in component counts to the config file in a way that avoids creating another variable/variable group. We can do this by changing the `component_list` under the DES parameters into a dictionary with component names as the key and component count as the value, like so:

```
discrete_event_parameters:
    component_list:
        nacelle : 1
        blade : 3
        tower : 1
        foundation : 1
    material_list:
        - glass fiber
        - epoxy
    seed: 13
    min_lifespan: 120 # Units: timesteps
    blade_weibull_L: 240
    blade_weibull_K: 2.2
    component_fixed_lifetimes:
      nacelle : 30
      blade : 20
      foundation : 50
      tower : 50
```

Then we change the way we access the component names to instantiate `Context`: 
`possible_components=[item for item,value in des_params.get('component_list').items()]`

and to run the diagnostic plots:
`keep_cols=[item for item,value in des_params.get('component_list').items()]`

Actually it might make more sense to pass in the dictionary to the diagnostic plots, instead of a list of component names, so we can use the values in scaling the component count inventories - I'm thinking convert the dictionary to a data frame, merge it with the inventory, and calculate the scaled counts, but there could be more efficient ways.

I know PR #89, which resolves the last issue before Release 1.0.0 is complete, is somewhat dependent on this PR, so if this proposal sounds reasonable I can take care of updating  & distributing the config file and making the necessary changes in main.py. Alicia, I can also take a crack at incorporating the component counts into the diagnostic viz plots if you'd like.

**Comment by akey7** [comment]
@rjhanes I just finished Issue #88, so you can no pull the latest changes from develop into this branch.

You will need a section of your YAML configuration like the following:

```yaml
output_filenames:
    costgraph_pickle: netw.obj
    costgraph_csv: netw.csv
    pathway_cost_history: pathway_cost_history.csv
    component_counts_plot: component_counts.png
    material_mass_plot: material_mass.png
    count_cumulative_histories: count_cumulative_histories.csv
    mass_cumulative_histories: mass_cumulative_histories.csv
```

**Comment by rjhanes** [comment]
@akey7 I added the scaling to the DiagnosticViz using a try/except statement so the scaling only happens for count inventories, not mass inventories. It's a bit roundabout but does seem to work.

**Comment by akey7** [comment]
I added a `print()` statement when the exception is caught in `DiagnosticViz` because it is good practice to log exception messages. I also reformatted the code slightly.

**Review by akey7 — APPROVED** [review]
Looks good to me! I made a comment on this PR. Let me know if you have questions!

**Comment by rjhanes** [comment]
That all makes sense, and good call on logging the exception. Thanks!

**Pull request merged**
